### ISSUE TITLE
雨裁的被动比例无法修改

### ISSUE THREAD

**Issue by Fachep** [wormtql/genshin_artifact#134]
![image](https://user-images.githubusercontent.com/31302548/160662089-178c79c8-7655-431f-bf86-d29460c5d13f.png)
edge 99.0.1150.55 无法修改此处的“被动应用比例”，无法拖动滑块，无法输入树脂，点击滑轨会变成NaN

**Comment by Fachep** [comment]
直接点击滑轨报错如下：
```
149.872bb680.js:1 
        
       panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: null, expected f64", line: 1, column: 231)', src\applications\calculator\interface_calculator.rs:73:67

Stack:

Error
    at j (https://www.mona-uranai.com/js/149.872bb680.js:1:10346)
    at https://www.mona-uranai.com/0cec7427a1bdde37.module.wasm:wasm-function[601]:0xe49ff
    at https://www.mona-uranai.com/0cec7427a1bdde37.module.wasm:wasm-function[2119]:0x111dc4
    at https://www.mona-uranai.com/0cec7427a1bdde37.module.wasm:wasm-function[851]:0xfa211
    at https://www.mona-uranai.com/0cec7427a1bdde37.module.wasm:wasm-function[997]:0x100f9a
    at https://www.mona-uranai.com/0cec7427a1bdde37.module.wasm:wasm-function[1527]:0x10d9c9
    at https://www.mona-uranai.com/0cec7427a1bdde37.module.wasm:wasm-function[1592]:0x10e8cd
    at https://www.mona-uranai.com/0cec7427a1bdde37.module.wasm:wasm-function[1032]:0x10239e
    at https://www.mona-uranai.com/0cec7427a1bdde37.module.wasm:wasm-function[45]:0x1929a
    at https://www.mona-uranai.com/0cec7427a1bdde37.module.wasm:wasm-function[1629]:0x10ef75


M @ 149.872bb680.js:1
$func601 @ 0cec7427a1bdde37.module.wasm:0xe4ad0
$func2119 @ 0cec7427a1bdde37.module.wasm:0x111dc4
$func851 @ 0cec7427a1bdde37.module.wasm:0xfa211
$func997 @ 0cec7427a1bdde37.module.wasm:0x100f9a
$func1527 @ 0cec7427a1bdde37.module.wasm:0x10d9c9
$func1592 @ 0cec7427a1bdde37.module.wasm:0x10e8cd
$func1032 @ 0cec7427a1bdde37.module.wasm:0x10239e
$func45 @ 0cec7427a1bdde37.module.wasm:0x1929a
$calculatorinterface_get_damage_analysis @ 0cec7427a1bdde37.module.wasm:0x10ef75
get_damage_analysis @ 149.872bb680.js:1
characterDamageAnalysis @ artifact-plan-page.7bb8be81.js:1
fn.get @ vue.min.js:6
fn.evaluate @ vue.min.js:6
(匿名) @ vue.min.js:6
i @ artifact-plan-page.7bb8be81.js:1
(匿名) @ composition-api@1.0.0-rc.3:15
Cn @ composition-api@1.0.0-rc.3:15
r.render @ composition-api@1.0.0-rc.3:15
e._render @ vue.min.js:6
r @ vue.min.js:6
fn.get @ vue.min.js:6
fn.run @ vue.min.js:6
un @ vue.min.js:6
(匿名) @ vue.min.js:6
qe @ vue.min.js:6
Promise.then(异步)
ze @ vue.min.js:6
Ye @ vue.min.js:6
(匿名) @ vue.min.js:6
fn.update @ vue.min.js:6
ce.notify @ vue.min.js:6
set @ vue.min.js:6
pn.set @ vue.min.js:6
callback @ chunk-vendors.28cb676e.js:16
He @ vue.min.js:6
n @ vue.min.js:6
He @ vue.min.js:6
e.$emit @ vue.min.js:6
setPosition @ chunk-vendors.28cb676e.js:16
setPosition @ chunk-vendors.28cb676e.js:16
onSliderClick @ chunk-vendors.28cb676e.js:16
He @ vue.min.js:6
n @ vue.min.js:6
Yr.o._wrapper @ vue.min.js:6
vue.min.js:6 
        
       RuntimeError: unreachable
    at 0cec7427a1bdde37.module.wasm:0xfa247
    at 0cec7427a1bdde37.module.wasm:0x100f9a
    at 0cec7427a1bdde37.module.wasm:0x10d9c9
    at 0cec7427a1bdde37.module.wasm:0x10e8cd
    at 0cec7427a1bdde37.module.wasm:0x10239e
    at 0cec7427a1bdde37.module.wasm:0x1929a
    at 0cec7427a1bdde37.module.wasm:0x10ef75
    at Function.get_damage_analysis (149.872bb680.js:1:7019)
    at a.characterDamageAnalysis (artifact-plan-page.7bb8be81.js:1:54979)
    at fn.get (vue.min.js:6:26768)
```
其余操作无报错
